-- Vehicle-repair subsystem, part 4 of 4: seed Nagole (NAG) catalog.
-- Categories + ~200 cleaned/deduped parts from the client's spare-parts
-- Excel (light cleanup of typos + obvious duplicates). NAG stock rows are
-- created at qty 0 — staff enter an opening stock-take in the UI, since the
-- source sheet logs receipts, not a reliable running balance.

INSERT INTO spare_part_categories (name, sort_order) VALUES
  ('Body & Panels', 0),
  ('Brakes', 1),
  ('Wheels & Tyres', 2),
  ('Suspension & Stand', 3),
  ('Battery, Charging & Electronics', 4),
  ('Switches & Wiring', 5),
  ('Lighting & Indicators', 6),
  ('Motor & Hub', 7),
  ('Locks & Security', 8),
  ('Controls & Handlebar', 9),
  ('Fasteners & Consumables', 10),
  ('Miscellaneous', 11);

INSERT INTO spare_parts (name, category_id)
VALUES
  ('10 M BOLTS 1.5 INCH', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('10M BOLTS 1 INCH', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('ANTI-THEFT LOCK', (SELECT id FROM spare_part_categories WHERE name = 'Locks & Security')),
  ('ANTITHEIFT', (SELECT id FROM spare_part_categories WHERE name = 'Locks & Security')),
  ('AXILE BOLTS NUTS', (SELECT id FROM spare_part_categories WHERE name = 'Wheels & Tyres')),
  ('BACK BRAKE LEVER', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('BACK BRAKE LINER S', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('BALL RACER SET', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('BATTERY 30AH', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('BATTERY 60AH', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('BEARINGS', (SELECT id FROM spare_part_categories WHERE name = 'Wheels & Tyres')),
  ('BODY CHROME TOP SIDE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('BOTTEM PANEL GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('BOTTOM PANEL MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('BOTTOM PANEL WHITE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('BRAKE CABLES', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('BRAKE CHROME', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('BRAKE LINERS', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('BRAKE PADS', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('CABLE TIES', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('CALIPER SET', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('CENTER STAND ASSEMBLY', (SELECT id FROM spare_part_categories WHERE name = 'Suspension & Stand')),
  ('CENTER STAND RUBBER', (SELECT id FROM spare_part_categories WHERE name = 'Suspension & Stand')),
  ('CHANGING SOCKETS', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('CHARGER', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('CHARGING SHOCKET', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('CHIP NUTS SILVER CHIPS', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('CHROME BEADING', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('CLIP NUTS', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('CONE SET', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('CONTROLLER', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('CRUISE SWITCH', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('CRUSSISCONTROI SWITCH', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('DC BOOKS', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('DC CONTROLLERS', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('DC CONVERTOR', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('DISC OIL', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('DISC PADS', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('DISC PLATE', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('DISC PLATE BOLTS', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('DISPLAY', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('DISPLAY 30AH', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('DISPLAY 60AH', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('ELE CASSIS 2.5', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('ELECTRIC TAPE', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('FLASHERS', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('FLOOR BOARD', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FLOOR PANEL', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FOOT BOARDS', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FORK ASSEMBLY', (SELECT id FROM spare_part_categories WHERE name = 'Suspension & Stand')),
  ('FROKE LEVER SPRING LH', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('FRONT BODY CHROME LH', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT BODY CHROME RH', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT BODY PANEL BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT BODY PANEL GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT BODY PANEL MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT BODY PANEL WHITE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT BODY REAR COVER', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT BRAKE ASSEMBLY', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('FRONT BRAKE PADS', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('FRONT BRAKE SET', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('FRONT CALIPERS', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('FRONT DISC PADS', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('FRONT DISC PLATE BOLTS', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('FRONT DISC PLATES', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('FRONT FORK', (SELECT id FROM spare_part_categories WHERE name = 'Suspension & Stand')),
  ('FRONT INDICATORS LH', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('FRONT INDICATORS RH', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('FRONT MUD GUARD CHROMES', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT MUDGUARD', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT MUDGUARD BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT MUDGUARD GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT MUDGUARD MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT MUDGUARD WHITE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT PANEL BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT PANEL CHROME RH/LH', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT PANEL GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT PANEL MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT PANEL WHITE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT REAR CHROME', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('FRONT TYRES', (SELECT id FROM spare_part_categories WHERE name = 'Wheels & Tyres')),
  ('FRONT WHEEL', (SELECT id FROM spare_part_categories WHERE name = 'Wheels & Tyres')),
  ('FRONT WHEEL AXL', (SELECT id FROM spare_part_categories WHERE name = 'Wheels & Tyres')),
  ('FRONT WHEEL BEARINGS', (SELECT id FROM spare_part_categories WHERE name = 'Wheels & Tyres')),
  ('FRONT WHEEL RIM', (SELECT id FROM spare_part_categories WHERE name = 'Wheels & Tyres')),
  ('GPS DEVICE', (SELECT id FROM spare_part_categories WHERE name = 'Locks & Security')),
  ('GRIP ASSEMBLY WITH', (SELECT id FROM spare_part_categories WHERE name = 'Controls & Handlebar')),
  ('HANDLE', (SELECT id FROM spare_part_categories WHERE name = 'Controls & Handlebar')),
  ('HANDLE BAR', (SELECT id FROM spare_part_categories WHERE name = 'Controls & Handlebar')),
  ('HANDLE BAR NUT AND BOLTS', (SELECT id FROM spare_part_categories WHERE name = 'Controls & Handlebar')),
  ('HEAD LAMP ASSEMBLY', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEAD LAMP CHROME', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEAD LAMP PANELS BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEAD LAMP SWITCHES', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEAD LIGHT', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEAD LIGHT ASSEMBLY', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEAD LIGHT CHROME', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEAD LIGHT DOMES', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEAD LIGHT PANEL MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEAD LIGHT PANEL TOP BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEAD LIGHT PANEL TOP GREY', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEAD LIGHT PANEL TOP MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEADLAMP BULB', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HEADLIGHT SWITCHES', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('HIGH BEAM SWITCHES', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('HIGH LOW BEAM SWITCHES', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('HORN', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('HORN SWITCHES', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('HUB CAME WITH BRAKE SHOE', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('HUB COVER WITH BRAKE', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('HUB COVER WITH BRAKE SHOE', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('HUB MOTOR COVER', (SELECT id FROM spare_part_categories WHERE name = 'Motor & Hub')),
  ('IGNITION LOCK SET', (SELECT id FROM spare_part_categories WHERE name = 'Locks & Security')),
  ('INDICATOR ASSEMBLY', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('INDICATOR HOLDER', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('INDICATOR LH', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('INDICATOR RH', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('INDICATOR SWITCHES', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('LADIES FOOT REST', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('LH BODY PANEL GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('LH BODY PANEL MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('LH BRAKE LEVER', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('LH BRAKE[ SWAPPING] 30 AH', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('LH LEVER', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('LH REAR BRAKE LEVER', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('LOCK SET', (SELECT id FROM spare_part_categories WHERE name = 'Locks & Security')),
  ('M10 25 BOLT', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('M10/25 BOLT', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('M3 CONNECTORS', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('MAIN SWITCHES', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('MAIN WIRING', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('MALE FEMALE CONNECTORS', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('MASTER CYLINDER', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('MCB', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('MEN FOOT REST', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('MIRROR', (SELECT id FROM spare_part_categories WHERE name = 'Controls & Handlebar')),
  ('MODE SWITCHES', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('MONITOR', (SELECT id FROM spare_part_categories WHERE name = 'Locks & Security')),
  ('MOTORS', (SELECT id FROM spare_part_categories WHERE name = 'Motor & Hub')),
  ('MUDGUARD REAR', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('NUMBER PLATE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('NUT AND BOLTS 10MM(M6*25)', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('REAR BODY PANEL BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('REAR BODY PANEL LH BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('REAR BODY PANEL LH GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('REAR BODY PANEL LH MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('REAR BODY PANEL LH WHITE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('REAR BODY PANEL RH BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('REAR BODY PANEL RH GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('REAR BODY PANEL RH MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('REAR BODY PANEL RH WHITE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('REAR BRAKE CABLE', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('REAR BRAKE SHOE', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('REAR FULL BODY PANEL GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('REAR HUB COVER', (SELECT id FROM spare_part_categories WHERE name = 'Motor & Hub')),
  ('REAR LAMP', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('REAR LAMP ASSEMBLY', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('REAR REFLECTOR', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('REAR SEAT WITH PLATE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('REAR SUSPENSION', (SELECT id FROM spare_part_categories WHERE name = 'Suspension & Stand')),
  ('REAR SUSPENSION BOLT', (SELECT id FROM spare_part_categories WHERE name = 'Suspension & Stand')),
  ('REAR SUSPENSION LH LEVERS', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('RELAYS', (SELECT id FROM spare_part_categories WHERE name = 'Battery, Charging & Electronics')),
  ('REVERSE SWITCHES', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('RH BODY PANEL MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('RH FRONT BRAKE LEVER', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('RH LEVER', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('RH MASTER CYLINDER', (SELECT id FROM spare_part_categories WHERE name = 'Brakes')),
  ('SAND PAPER', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('SB 75 CABLES', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('SB 75 CONNECTORS', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('SB 75 POWER CABLE', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring')),
  ('SEAT LOCK ASSEMBLY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SHROUD PANEL BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SHROUD PANEL GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SHROUD PANEL MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SHROUD PANEL WHITE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SIDE INDICATORS', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('SIDE PANEL LH BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SIDE PANEL LH GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SIDE PANEL LH MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SIDE PANEL LH WHITE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SIDE PANEL RH BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SIDE PANEL RH GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SIDE PANEL RH MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SIDE PANEL RH WHITE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SIDE STAND', (SELECT id FROM spare_part_categories WHERE name = 'Suspension & Stand')),
  ('SIDE STAND BOLT', (SELECT id FROM spare_part_categories WHERE name = 'Suspension & Stand')),
  ('SIDE STAND SPRING', (SELECT id FROM spare_part_categories WHERE name = 'Suspension & Stand')),
  ('SMALL SCREWS', (SELECT id FROM spare_part_categories WHERE name = 'Fasteners & Consumables')),
  ('SWING REAR PANEL BLACK', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SWING REAR PANEL GREY', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SWING REAR PANEL MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('SWING REAR PANEL WHITE', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('TAIL LAMP PANEL MAROON', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('TAIL LAMP PANEL WHITE', (SELECT id FROM spare_part_categories WHERE name = 'Lighting & Indicators')),
  ('THROTTLE', (SELECT id FROM spare_part_categories WHERE name = 'Controls & Handlebar')),
  ('TOOL BOXPANEL', (SELECT id FROM spare_part_categories WHERE name = 'Body & Panels')),
  ('VTD DEVICE', (SELECT id FROM spare_part_categories WHERE name = 'Locks & Security')),
  ('X/P SWITCHES', (SELECT id FROM spare_part_categories WHERE name = 'Switches & Wiring'));

-- Opening NAG stock rows (qty 0) for every catalog part.
INSERT INTO spare_part_stock (hub_id, spare_part_id)
SELECT h.id, sp.id
FROM spare_parts sp
CROSS JOIN (SELECT id FROM hubs WHERE code = 'NAG' AND deleted_at IS NULL) h
WHERE sp.deleted_at IS NULL
ON CONFLICT DO NOTHING;
